import React from "react";
import { Box, Typography, Table, TableBody, TableCell, TableRow, TableContainer, Paper } from "@mui/material";

const CustomerInfo = ({ data }) => {
  return (
    <Box>
      <Typography fontWeight="bold" fontSize="12px">
        Customer Information
      </Typography>

      <TableContainer sx={{ border: "1px solid #ccc", borderRadius: "5px" }}>
        <Table size="small" sx={{ '& .MuiTableCell-root': { py: 0 } }}>
          <TableBody>
            <TableRow sx={{ '& .MuiTableCell-root': { py: 0 } }}>
              <TableCell sx={{ backgroundColor: "#f9fafb", py: 0.5, width: "17%" }}>
                <Typography fontSize="10px" fontWeight="bold" >
                  Meter ID:
                </Typography>
              </TableCell>
              <TableCell sx={{ py: 0.5, width: "17%" }}>
                <Typography fontSize="10px" fontWeight="bold" >
                  {data?.firstMeter ? (data.firstMeter.includes('(') ? data.firstMeter.split('(')[1]?.replace(')', '') : data.firstMeter) : ''}
                </Typography>
              </TableCell>
              <TableCell rowSpan={5} sx={{ backgroundColor: "#f9fafb", py: 0.5, width: "13%" }}>
                <Typography fontSize="10px" fontWeight="bold" >
                  Address:
                </Typography>
              </TableCell>
              <TableCell rowSpan={5} sx={{ py: 0.5, width: "17%" }}>
                <Typography fontSize="10px"  >
                  {data.address}
                </Typography>
              </TableCell>
              {/* <TableCell sx={{ backgroundColor: "#f9fafb", py: 0.5, width: "13%" }}>
                <Typography fontSize="10px"  fontWeight="bold" >
                  Tenant Emergency Contact:
                </Typography>
              </TableCell>
              <TableCell sx={{ py: 0.5, width: "17%" }}>
                <Typography fontSize="10px"  >
                  {data.tenantEmergencyContact}
                </Typography>
              </TableCell> */}

            </TableRow>
            <TableRow sx={{ '& .MuiTableCell-root': { py: 0 } }}>
              <TableCell sx={{ backgroundColor: "#f9fafb", py: 0.5, width: "17%" }}>
                <Typography fontSize="10px" fontWeight="bold" >
                  Meter Name:
                </Typography>
              </TableCell>
              <TableCell sx={{ py: 0.5, width: "17%" }}>
                <Typography fontSize="10px"  >
                  {data.meterLableName}
                </Typography>
              </TableCell>
            </TableRow>
            <TableRow sx={{ '& .MuiTableCell-root': { py: 0 } }}>
            </TableRow>
            <TableRow sx={{ '& .MuiTableCell-root': { py: 0 } }}>
              <TableCell sx={{ backgroundColor: "#f9fafb", py: 0.5, width: "17%" }}>
                <Typography fontSize="10px" fontWeight="bold" >
                  Building Name:
                </Typography>
              </TableCell>
              <TableCell sx={{ py: 0.5, width: "17%" }}>
                <Typography fontSize="10px"  >
                  {data.buildingName}
                </Typography>
              </TableCell>
            </TableRow>
            <TableRow sx={{ '& .MuiTableCell-root': { py: 0 } }}>
            <TableCell sx={{ backgroundColor: "#f9fafb", py: 0.5, width: "17%" }}>
                <Typography fontSize="10px"  fontWeight="bold" >
                  Organization Name:
                </Typography>
              </TableCell>
              <TableCell sx={{ py: 0.5, width: "17%" }}>
                <Typography fontSize="10px"  >
                  {data.orgName}
                </Typography>
              </TableCell>
            </TableRow>
            <TableRow sx={{ '& .MuiTableCell-root': { py: 0 } }}>
              <TableCell colSpan={4} sx={{ width: "17%" }}>
                <Typography
                  variant="caption"
                  color="text.secondary"
                  fontSize="10px"
                  sx={{ lineHeight: 1 }} // or try 1.1 or even 1 for tighter spacing                
                >
                  This electricity bill format is automatically generated by M/s. Skylights Energy. It should be noted that the data presented here does not hold any legal validity or can be used for any legal claims. It is not intended to replicate any ESCOM bills and does not serve as a duplicate. The information displayed is extracted from energy analytics software and is limited to the extracted data, without providing any guarantees or legal implications.
                </Typography>
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </TableContainer>
    </Box>
  );
};

export default CustomerInfo;

