import React from 'react';
import { Box, Button } from '@mui/material';

const BillTemplate = ({ data }) => {
  const handlePrint = () => {
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(\`
        <!DOCTYPE html>
        <html>
          <head>
            <title>Electricity Bill</title>
            <style>
              body { 
                margin: 0; 
                padding: 20px;
                font-family: Arial, sans-serif;
              }
              @media print {
                body { padding: 0; }
                table { page-break-inside: avoid; }
                img { max-width: 100%; }
              }
              .container {
                padding: 20px;
                max-width: 100%;
                margin: auto;
                margin-bottom: 40px;
                border: 2px solid #000;
                background-color: #fff;
              }
              table {
                width: 100%;
                border-collapse: collapse;
                margin-bottom: 15px;
                border: 1px solid #000;
              }
              th, td {
                padding: 8px;
                border: 1px solid #000;
                text-align: left;
              }
              th {
                background-color: #f5f5f5;
              }
              .info-table th {
                width: 25%;
              }
              .highlight {
                color: #1976d2;
              }
              .expand-column {
                width: 30%;
              }
              h5 {
                margin-top: 5px;
                margin-bottom: 3px;
                text-decoration: underline;
              }
              hr {
                border: 1px solid #000;
                margin: 15px 0;
              }
              .text-right {
                text-align: right;
              }
            </style>
          </head>
          <body>
            \${data.map(renderBill).join('')}
            <script>
              window.onload = function() {
                window.print();
                window.onafterprint = function() {
                  window.close();
                };
              }
            </script>
          </body>
        </html>
      \`);
      printWindow.document.close();
    }
  };

  const renderBill = (row) => {
    return \`
      <div class="container">
        <!-- Header Section -->
        <div class="header">
          <div style="display: flex; justify-content: space-between">
            <img src="/skylightsenergyLOGO.png" alt="SkyLights Energy logo" style="width: 250px; height: 30px" />
            <p>Harnessing Tech x Driven Power</p>
          </div>
          <p style="display: flex; justify-content: space-between">www.skylightenergy.in</p>
          <p style="display: flex; justify-content: space-between"><span>info@skylightsenergy.in</span> +91-9100010019</p>
          <p style="display: flex; justify-content: space-between">
            No. 15 1st Cross, 3rd Main Begur Rd,Bommanahalli Bangalore 560068, KA India 
            <span>GSTIN:29ACGFS8716B1ZZ</span>
          </p>
          <hr>
        </div>

        <!-- Building Information -->
        <table class="info-table">
          <tbody>
            <tr>
              <th>Building Name:</th>
              <td>P LEELA</td>
            </tr>
            <tr>
              <th>Address:</th>
              <td colspan="3">
                No 437, Kh No 336/437/17th Cross, HSR Layout 4th Sector, Bangalore 560102
              </td>
            </tr>
            <tr>
              <th>Tenant Floor:</th>
              <td></td>
              <th>Tenant Meter ID:</th>
              <td>\${row.firstMeter}</td>
            </tr>
            <tr>
              <th>Tenant Name & Contact:</th>
              <td class="highlight" colspan="3">FULL BUILDING</td>
            </tr>
            <tr>
              <th>Tenant Since Date:</th>
              <td>01/05/23</td>
              <th>Tenant Emergency Contact:</th>
              <td></td>
            </tr>
            <tr>
              <td colspan="4" style="font-size: 12px; text-align: justify">
                This electricity bill format is automatically generated by M/s. Skylights Energy. It should be noted that the data presented here
                does not hold any legal validity or can be used for any legal claims. It is not intended to replicate any ESCOM bills and does not
                serve as a duplicate. The information displayed is extracted from energy analytics software and is limited to the extracted data,
                without providing any guarantees or legal implications.
              </td>
            </tr>
          </tbody>
        </table>

        <!-- Billing Information -->
        <table>
          <thead>
            <tr>
              <th>RR No.</th>
              <th>Account ID</th>
              <th>Bill No</th>
              <th>Billing Period</th>
              <th>Bill Date</th>
              <th>Due Date</th>
              <th>Discount Date</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>6262859450</td>
              <td>FULL BUILDING</td>
              <td>SKYLIGHTS SL NO.</td>
              <td>\${row.period}</td>
              <td>\${row.billDate}</td>
              <td>\${row.dueDate}</td>
              <td>\${row.discDate}</td>
            </tr>
          </tbody>
        </table>

        <!-- Additional Information -->
        <table>
          <thead>
            <tr>
              <th colspan="1">Name & Address:</th>
              <th colspan="8">
                P LEELA ADDRESS: No 437, Kh No 336/43717TH CROSS, HSR LAYOUT 4TH SECTOR BANGALORE 560102
              </th>
            </tr>
            <tr>
              <th colspan="1">Tariff</th>
              <th colspan="4">\${row.tariff || 'Commercial 1HT2B'}</th>
              <th colspan="1">Wheeling Energy</th>
              <th colspan="3" class="expand-column">0</th>
            </tr>
            <tr>
              <th colspan="1">Contract Demand (KVA)</th>
              <th colspan="4">110</th>
              <th colspan="1">Special Energy</th>
              <th colspan="3" class="expand-column">0</th>
            </tr>
            <tr>
              <th colspan="1">90% of CD (KVA)</th>
              <th colspan="4">99</th>
              <th colspan="1">Base Consumption</th>
              <th colspan="3" class="expand-column">0</th>
            </tr>
            <tr>
              <th colspan="1">Recorded Demand (KVA)</th>
              <th colspan="4">51</th>
              <th colspan="1">Power Cut</th>
              <th colspan="3" class="expand-column">0</th>
            </tr>
            <tr>
              <th colspan="1">Billing Demand (KVA)</th>
              <th colspan="4">99</th>
              <th rowspan="2" colspan="1">Power Cut Energy Entitlement<br/>Demand Entitlement</th>
              <th rowspan="2" colspan="3" class="expand-column">0</th>
            </tr>
            <tr>
              <th colspan="1">Type</th>
              <th colspan="4">Commercial 1HT2B</th>
            </tr>
          </thead>
        </table>

        <!-- Meter Readings -->
        <h5>Meter Readings:</h5>
        <table>
          <thead>
            <tr>
              <th>Description</th>
              <th>EB Meter</th>
              <th>DG Meter</th>
              <th>MD Meter</th>
              <th>PF</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Present Reading (01-11-2024)</td>
              <td>\${row.eb_present}</td>
              <td>846.36</td>
              <td>1.00</td>
              <td></td>
            </tr>
            <tr>
              <td>Previous Reading (01-10-2024)</td>
              <td>\${row.eb_previous}</td>
              <td>811.48</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <td>Difference</td>
              <td>\${row.netConsumption}</td>
              <td>34.88</td>
              <td>-</td>
              <td></td>
            </tr>
            <tr>
              <td>Meter Constant</td>
              <td>1</td>
              <td>1</td>
              <td>1</td>
              <td></td>
            </tr>
            <tr>
              <td>Consumption</td>
              <td>2,987.95</td>
              <td>34.88</td>
              <td>-</td>
              <td></td>
            </tr>
            <tr>
              <td>Less/Add: Consumption</td>
              <td>257.94</td>
              <td>1.50</td>
              <td></td>
              <td></td>
            </tr>
            <tr>
              <td>Net Consumption</td>
              <td>3,245.89</td>
              <td>36.39</td>
              <td>-</td>
              <td>1.00</td>
            </tr>
          </tbody>
        </table>

        <!-- TOD Meter Readings -->
        <h5>TOD meter readings for meter</h5>
        <table>
          <thead>
            <tr>
              <th>Time Zone</th>
              <th>Name of the Zone</th>
              <th>Present Readings</th>
              <th>Previous Readings</th>
              <th>Consumption</th>
              <th>MD Reading</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>06:00 Hrs to 10:00Hrs</td>
              <td>Morning Peak</td>
              <td>-</td>
              <td>-</td>
              <td>-</td>
              <td>-</td>
            </tr>
            <tr>
              <td>10:00 Hrs to 18:00Hrs</td>
              <td>Normal</td>
              <td>-</td>
              <td>-</td>
              <td>-</td>
              <td>-</td>
            </tr>
            <tr>
              <td>18:00 Hrs to 22:00Hrs</td>
              <td>On Peak</td>
              <td>-</td>
              <td>-</td>
              <td>-</td>
              <td>-</td>
            </tr>
            <tr>
              <td>22:00 Hrs to 06:00Hrs</td>
              <td>Off Peak</td>
              <td>-</td>
              <td>-</td>
              <td>-</td>
              <td>-</td>
            </tr>
          </tbody>
        </table>

        <!-- Detailed Bill -->
        <h5>Your Detailed Bill</h5>
        <table>
          <tbody>
            <tr>
              <th>Description</th>
              <th>Amount (Rs.)</th>
            </tr>
            <tr>
              <td>Demand Charges: \${row.contractDemand} KVA Rs./KVA 365.00</td>
              <td class="text-right">₹\${row.demandCharges}</td>
            </tr>
            <tr>
              <td>Energy Charges: \${row.netConsumption} KWh Rs./KWh 8.00</td>
              <td class="text-right">₹\${row.energyCharges}</td>
            </tr>
            <tr>
              <td>Fuel Cost Adj \${row.netConsumption} KWh Rs./KWh 0.00</td>
              <td class="text-right">₹-</td>
            </tr>
            <tr>
              <td>Interest on Revenue</td>
              <td class="text-right">₹\${row.interOnReven}</td>
            </tr>
            <tr>
              <td>Interest on Tax</td>
              <td class="text-right">₹\${row.interOnTax}</td>
            </tr>
            <tr>
              <td>Tax 9%</td>
              <td class="text-right">₹\${row.tax}</td>
            </tr>
            <tr>
              <td>Current Bill Amount</td>
              <td class="text-right">₹\${row.currentBillAmount}</td>
            </tr>
            <tr>
              <td>Arrears</td>
              <td class="text-right">₹-</td>
            </tr>
            <tr>
              <td>Bill Correction</td>
              <td class="text-right">₹-</td>
            </tr>
            <tr>
              <td>FAC Short claim adjustment</td>
              <td class="text-right">₹-</td>
            </tr>
            <tr>
              <td>Bill rounding adjustment</td>
              <td class="text-right">₹-</td>
            </tr>
            <tr>
              <td><b>Net EB Payable Amount</b></td>
              <td class="text-right"><b>₹\${row.currentBillAmount}</b></td>
            </tr>
            <tr>
              <td><b>DG Energy 118.08 KWh Rs./KWh 80.00</b></td>
              <td class="text-right">₹9,447</td>
            </tr>
            <tr>
              <td><b>Total Payable Amount</b></td>
              <td class="text-right"><b>₹\${parseFloat(row.currentBillAmount) + 9447}</b></td>
            </tr>
          </tbody>
        </table>

        <!-- Footer -->
        <hr>
        <div style="display: flex; justify-content: space-around">
          <img src="/Switchonomy.png" alt="Switchonomy Logo" style="width: auto; height: 40px;" />
          <img src="/Switchology.png" alt="Switchology Logo" style="width: auto; height: 40px;" />
        </div>
      </div>
    \`;
  };

  return (
    <Box>
      <Button 
        variant="contained" 
        color="primary" 
        onClick={handlePrint} 
        sx={{ mb: 2 }}
      >
        Download PDF
      </Button>
      <div style={{ border: '2px solid #000', padding: '20px', backgroundColor: '#fff' }}>
        <div dangerouslySetInnerHTML={{ __html: data.map(renderBill).join('') }} />
      </div>
    </Box>
  );
};

export default BillTemplate; 
